version: '3.5'

services:
  rabbitmq:
    image: rabbitmq:3.7.14
    env_file:
      - ./docker/rabbitmq.env
    ports:
      - "8080:15672"
      - "5672:5672"
    hostname: "ricc-rabbit"

  django:
    image: django
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: db run
    ports:
      - "8000:8000"
    volumes:
      - ./src/:/src/
#     networks:
#       - napoleon-ricc-network

# networks:
#   napoleon-ricc-network:
#     external: true
