version: '3.5'

services:
  redis:
    image: redis:2.8
    ports:
      - "6379:6379"
    hostname: "ricc-redis"

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - ./docker/rabbitmq.env
    ports:
      - "8080:15672"
      - "5672:5672"
    hostname: "ricc-rabbit"
    volumes:
      - rabbit_data:/var/lib/rabbitmq/

  django:
    image: django
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: db run
    ports:
      - "8000:8000"
    volumes:
      - ./src/:/src/
#     networks:
#       - napoleon-ricc-network

volumes:
  rabbit_data:

# networks:
#   napoleon-ricc-network:
#     external: true
