# Generated by Django 2.2.1 on 2019-05-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('hash', models.CharField(max_length=128)),
                ('auth_token', models.CharField(max_length=64)),
            ],
        ),
    ]
