# Generated by Django 2.2.1 on 2019-06-02 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Central',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=64)),
                ('automatic_irrigation', models.BooleanField(verbose_name='Automatic Irrigation Status')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('hash', models.CharField(max_length=128)),
                ('auth_token', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('data_token', models.CharField(max_length=64)),
                ('central', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station', to='ricc.Central')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='central',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centrals', to='ricc.User'),
        ),
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('data_token', models.CharField(max_length=64)),
                ('status', models.BooleanField(verbose_name='Actuator Status')),
                ('central', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuator', to='ricc.Central')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
