# Generated by Django 2.2.1 on 2019-06-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnlockedCentral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='actuator',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='central',
            name='mac_address',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
