# Generated by Django 2.2.2 on 2019-06-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricc', '0002_auto_20190607_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Network Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actuator',
            name='status',
            field=models.BooleanField(verbose_name='Network Status'),
        ),
    ]
