# Generated by Django 2.2.2 on 2019-06-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricc', '0003_auto_20190628_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Network Status'),
        ),
        migrations.AlterField(
            model_name='station',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Network Status'),
        ),
    ]
